"""add agent column to embeddings

Revision ID: 1ad31a3a4213
Revises: ac09a18d51d3
Create Date: 2026-04-09 20:24:09.915797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad31a3a4213'
down_revision: Union[str, Sequence[str], None] = 'ac09a18d51d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('agent', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_embeddings_agent'), 'embeddings', ['agent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_agent'), table_name='embeddings')
    op.drop_column('embeddings', 'agent')
    # ### end Alembic commands ###
