"""add indexes on project_name and user

Revision ID: 2773e984198b
Revises: 4efb13cb7aed
Create Date: 2026-04-09 18:47:39.322560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2773e984198b'
down_revision: Union[str, Sequence[str], None] = '4efb13cb7aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_embeddings_project_name'), 'embeddings', ['project_name'], unique=False)
    op.create_index(op.f('ix_embeddings_user'), 'embeddings', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_user'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_project_name'), table_name='embeddings')
    # ### end Alembic commands ###
