"""add project_name and user to embeddings

Revision ID: 4efb13cb7aed
Revises: e09975821e7f
Create Date: 2026-04-09 18:45:49.291862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4efb13cb7aed'
down_revision: Union[str, Sequence[str], None] = 'e09975821e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('project_name', sa.String(length=200), nullable=True))
    op.add_column('embeddings', sa.Column('user', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddings', 'user')
    op.drop_column('embeddings', 'project_name')
    # ### end Alembic commands ###
