"""add file_uploads table

Revision ID: ae22f01f608b
Revises: 1ad31a3a4213
Create Date: 2026-04-09 22:26:45.962830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae22f01f608b'
down_revision: Union[str, Sequence[str], None] = '1ad31a3a4213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('user', sa.String(length=200), nullable=True),
    sa.Column('agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_uploads_agent'), 'file_uploads', ['agent'], unique=False)
    op.create_index(op.f('ix_file_uploads_created_at'), 'file_uploads', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_uploads_project_name'), 'file_uploads', ['project_name'], unique=False)
    op.create_index(op.f('ix_file_uploads_user'), 'file_uploads', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_uploads_user'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_project_name'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_created_at'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_agent'), table_name='file_uploads')
    op.drop_table('file_uploads')
    # ### end Alembic commands ###
