"""add index on created_at

Revision ID: e44cbc66db5c
Revises: 2773e984198b
Create Date: 2026-04-09 18:48:48.886558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44cbc66db5c'
down_revision: Union[str, Sequence[str], None] = '2773e984198b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_embeddings_created_at'), 'embeddings', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_created_at'), table_name='embeddings')
    # ### end Alembic commands ###
